In [16]:
import numpy as np
import random
np_arr = np.random.randint(0,10,(5, 5))
n = 2  
print(f"Initial array: \n{np_arr}")
print(f"Sorted array: \n{np_arr[np_arr[:,n].argsort()]}")

Initial array: 
[[1 0 1 7 8]
 [8 9 5 1 0]
 [1 7 3 6 1]
 [1 6 7 7 4]
 [7 4 6 3 5]]
Sorted array: 
[[1 0 1 7 8]
 [1 7 3 6 1]
 [8 9 5 1 0]
 [7 4 6 3 5]
 [1 6 7 7 4]]


In [8]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [9]:
np_arr = np.arange(20)
print(np_arr)
np_arr[(9 <= np_arr) & (np_arr <= 15)] *= -1
print(np_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


In [14]:
np_arr = np.random.randint(0, 30, (5, 5))

print(np_arr)

np_arr_new = np.array([[np_arr[0][2], np_arr[0][3]], [np_arr[1][2], np_arr[1][3]]])

print(np_arr_new)

[[ 9  3 12  9  0]
 [ 7 14  1 29 28]
 [10 19 23  9 27]
 [ 9 17  3  5 12]
 [25  2 24  4 11]]
[[12  9]
 [ 1 29]]


In [17]:
np_arr = np.random.randint(0, 20, (5, 5))

print(np_arr)
print(np.nan)
for i in range(5):
    for j in range(5):
        a = random.randint(0, 20)
        if np_arr[i][j] == a:
            np_arr[i][j] = np.nan
print(np_arr)
    


[[ 0  1  2  9  5]
 [10 13  8  6  4]
 [ 4 15  5  3 15]
 [ 0  5  2 12 18]
 [ 8 14 14 11  4]]


ValueError: cannot convert float NaN to integer